(library (melt resourse welcome welcome)
  (export index-page)
  (import (scheme)
		  ())

  (define index-page (create-page 'index
								  (lambda ()
									`(html
									  (head (meta (@ (charset "UTF-8")))
											(meta (@ (name "viewport")
													 (content "width=device-width, initial-scale=1")))
											(link (@ (rel "stylesheet")
													 (href "asset/bulma/css/bulma.min.css")))
											(title "Welcome page"))
									  ;; welcome information
									  (section (@ (class "hero is-dark is-bold has-text-centered"))
											   (div (@ (class "hero-body"))
													(h1 (@ (class "title"))
														"welcome to Melt!!")
													(h2 (@ (class "subtitle"))
														"The Meta Local Note System.")))
									  ;; main content
									  (section (@ (class "section"))
											   (div (@ (class "container"))
													(div (@ (class "tile is-ancestor"))
														 (div (@ (class "tile is-4 is-vertical is-parent"))
															  (div (@ (class "tile is-child content box"))
																   (h1 (@ (class "title"))
																	   "Features")
																   (hr)
																   (p "this is what melt own now")
																   (ul (li "totaly user defined!")
																	   (li "use scheme language As DSL")
																	   (li "mostly flexible")))
															  (div (@ (class "tile content is-child box"))
																   (h1 (@ (class "title "))
																	   "To Do List")
																   (hr)
																   (ol (@ (type "i"))
																	   (li "Add comman markdown parser!")
																	   (li "Complete the init and execute command!")
																	   (li "well, add more components!")
																	   (li "define the data transformed between this elements!"))))
														 (div (@ (class "tile is-parent"))
															  (div (@ (class "tile is-child box"))
																   (h2 (@ (class "title"))
																	   "Hello World")
																   (p (@ (class "subtitle"))
																	  "You just init your first"
																	  (strong  " melt")
																	  "local web page!")
																   (hr)
																   (div (@ (class "content"))
																		(h2 (@ (class "title"))
																			"So what's Melt")
																		(p (@ (class "is-medium"))
																		   "Melt is generated from flax, inspired by gnu haunt. "
																		   "So, it's a static site generator. "
																		   "But, now i plan to build it as one Note system using MarkDown."
																		   "I am now making the markdown parser for this system. it will be fun!")
																		(h2 (@ (class "title"))
																			"30 Seconds to use a theme!")
																		(p (@ (class "is-medium"))
																		   "if you want to develop theme for melt, this is not the right place! "
																		   "Go to The doc page For more information.")
																		(p (@ (class "is-medim"))
																		   "So Let's begin!")
																		(h3 "use init")
																		(p "You can use")
																		(blockquote "melt init")
																		(p "to init a new Note Book. "
																		   "But it now is just a static site generator. I'm configuring "
																		   "the way to organize the note book. So, now, temporarily, it's just "
																		   "Another blog site.")
																		(h3 "use execute")
																		(p "to generate the output page, you can type this in linux shell.")
																		(blockquote "melt execute")
																		(p "this command will execute the predefined execute sequence.")))))))))
								  '()))
  )
